-- Reference schema for the dedicated Jonah 1:1-10 backend.
create extension if not exists btree_gist with schema extensions;

create table public.jonah_haftorah_1_1_10_highlight_groups_v1 (
  id bigint generated by default as identity primary key,
  verse integer not null check (verse between 1 and 10),
  start_word integer not null check (start_word >= 0),
  end_word integer not null check (end_word >= start_word),
  color integer not null check (color in (1, 2)),
  created_at timestamptz not null default now(),
  unique (verse, start_word, end_word),
  exclude using gist (verse with =, int4range(start_word, end_word, '[]') with &&)
);

create table public.jonah_haftorah_1_1_10_group_recordings_v1 (
  highlight_group_id bigint primary key references public.jonah_haftorah_1_1_10_highlight_groups_v1(id) on delete cascade,
  object_path text not null unique check (object_path ~ '^groups/[0-9]+\.(webm|ogg|mp4)$'),
  mime_type text not null check (mime_type in ('audio/webm', 'audio/ogg', 'audio/mp4')),
  byte_size bigint not null check (byte_size > 0 and byte_size <= 52428800),
  updated_at timestamptz not null default now()
);

alter table public.jonah_haftorah_1_1_10_highlight_groups_v1 enable row level security;
alter table public.jonah_haftorah_1_1_10_group_recordings_v1 enable row level security;
grant select, insert, delete on public.jonah_haftorah_1_1_10_highlight_groups_v1 to anon, authenticated;
grant usage, select on sequence public.jonah_haftorah_1_1_10_highlight_groups_v1_id_seq to anon, authenticated;
grant select, insert, update, delete on public.jonah_haftorah_1_1_10_group_recordings_v1 to anon, authenticated;

create policy jonah_haftorah_groups_read on public.jonah_haftorah_1_1_10_highlight_groups_v1 for select to anon, authenticated using (true);
create policy jonah_haftorah_groups_insert on public.jonah_haftorah_1_1_10_highlight_groups_v1 for insert to anon, authenticated with check (verse between 1 and 10 and start_word >= 0 and end_word >= start_word and color in (1, 2));
create policy jonah_haftorah_groups_delete on public.jonah_haftorah_1_1_10_highlight_groups_v1 for delete to anon, authenticated using (true);
create policy jonah_haftorah_recordings_read on public.jonah_haftorah_1_1_10_group_recordings_v1 for select to anon, authenticated using (true);
create policy jonah_haftorah_recordings_insert on public.jonah_haftorah_1_1_10_group_recordings_v1 for insert to anon, authenticated with check (exists (select 1 from public.jonah_haftorah_1_1_10_highlight_groups_v1 g where g.id = highlight_group_id));
create policy jonah_haftorah_recordings_update on public.jonah_haftorah_1_1_10_group_recordings_v1 for update to anon, authenticated using (true) with check (exists (select 1 from public.jonah_haftorah_1_1_10_highlight_groups_v1 g where g.id = highlight_group_id));
create policy jonah_haftorah_recordings_delete on public.jonah_haftorah_1_1_10_group_recordings_v1 for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('jonah-haftorah-1-1-10-group-recordings-v1', 'jonah-haftorah-1-1-10-group-recordings-v1', true, 52428800, array['audio/webm', 'audio/ogg', 'audio/mp4']);
create policy jonah_haftorah_audio_select on storage.objects for select to anon, authenticated using (bucket_id = 'jonah-haftorah-1-1-10-group-recordings-v1');
create policy jonah_haftorah_audio_insert on storage.objects for insert to anon, authenticated with check (bucket_id = 'jonah-haftorah-1-1-10-group-recordings-v1' and name ~ '^groups/[0-9]+\.(webm|ogg|mp4)$');
create policy jonah_haftorah_audio_update on storage.objects for update to anon, authenticated using (bucket_id = 'jonah-haftorah-1-1-10-group-recordings-v1') with check (bucket_id = 'jonah-haftorah-1-1-10-group-recordings-v1' and name ~ '^groups/[0-9]+\.(webm|ogg|mp4)$');
create policy jonah_haftorah_audio_delete on storage.objects for delete to anon, authenticated using (bucket_id = 'jonah-haftorah-1-1-10-group-recordings-v1');

